(()=>{
  if(!window.Chart)return;
  Chart.defaults.font.family='IBM Plex Mono, monospace';Chart.defaults.font.size=10;Chart.defaults.color='#72716c';
  const grid='rgba(20,21,23,.10)',ink='#141517',signal='#ff4d17',verified='#27b978',held='#e9a536',technical='#58b9d6';
  const coverage=document.getElementById('coverageChart');if(coverage)new Chart(coverage,{type:'radar',data:{labels:['Overall line','Overall branch','Flow','Guard auth','Guard enforcement','Bus protocol','Quality gate'],datasets:[{label:'Measured',data:[83.29,64.52,100,92.31,85.65,89.8,87.84],borderColor:signal,backgroundColor:'rgba(255,77,23,.10)',pointBackgroundColor:signal,borderWidth:2},{label:'Policy floor',data:[82,63,95,80,80,80,75],borderColor:'rgba(20,21,23,.28)',backgroundColor:'rgba(20,21,23,.02)',pointRadius:2,borderDash:[5,5]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:10,boxHeight:10}}},scales:{r:{min:55,max:100,ticks:{display:false},grid:{color:grid},angleLines:{color:grid},pointLabels:{color:ink,font:{size:9}}}}}});
  const behavior=document.getElementById('behaviorChart');if(behavior)new Chart(behavior,{type:'bar',data:{labels:['Detection','Specific detection','False positives','Held for approval'],datasets:[{label:'Strict',data:[100,100,0,71.4],backgroundColor:ink,borderWidth:0},{label:'Balanced',data:[100,100,0,14.3],backgroundColor:signal,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:'y',plugins:{legend:{position:'bottom',labels:{boxWidth:10,boxHeight:10}}},scales:{x:{min:0,max:100,grid:{color:grid},ticks:{callback:v=>v+'%'}},y:{grid:{display:false}}}}});
  const latency=document.getElementById('latencyChart');if(latency)new Chart(latency,{type:'line',data:{labels:['p50','p95','p99'],datasets:[{label:'Composed fence latency (ms)',data:[10.809,12.887,17.219],borderColor:technical,backgroundColor:'rgba(88,185,214,.08)',fill:true,tension:.28,pointBackgroundColor:technical,pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:grid},ticks:{callback:v=>v+' ms'}}}}});
  const assurance=document.getElementById('assuranceChart');if(assurance)new Chart(assurance,{type:'doughnut',data:{labels:['Compatibility','Fuzz / chaos','Release certification','Container scan'],datasets:[{data:[100,100,100,100],backgroundColor:[verified,technical,signal,held],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'72%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,boxHeight:10}}}}});
})();
