(()=>{
  if(!window.Chart)return;
  Chart.defaults.font.family='IBM Plex Mono, monospace';Chart.defaults.font.size=10;Chart.defaults.color='#687386';Chart.defaults.animation.duration=800;
  const grid='rgba(17,20,27,.075)',ink='#202633',accent='#5d6fff',accentSoft='rgba(93,111,255,.10)',verified='#18896b',held='#a87517',technical='#5c8fd8',muted='#a8b0be';
  const legend={position:'bottom',labels:{boxWidth:8,boxHeight:8,usePointStyle:true,pointStyle:'circle',padding:18,color:'#687386'}};
  const coverage=document.getElementById('coverageChart');if(coverage)new Chart(coverage,{type:'radar',data:{labels:['Overall line','Overall branch','Flow','Guard auth','Guard enforcement','Bus protocol','Quality gate'],datasets:[{label:'Measured',data:[83.29,64.52,100,92.31,85.65,89.8,87.84],borderColor:accent,backgroundColor:accentSoft,pointBackgroundColor:accent,pointBorderColor:'#fff',pointRadius:3,borderWidth:1.6},{label:'Policy floor',data:[82,63,95,80,80,80,75],borderColor:muted,backgroundColor:'rgba(168,176,190,.025)',pointRadius:0,borderWidth:1,borderDash:[4,5]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend},scales:{r:{min:55,max:100,ticks:{display:false},grid:{color:grid},angleLines:{color:grid},pointLabels:{color:ink,font:{size:9}}}}}});
  const behavior=document.getElementById('behaviorChart');if(behavior)new Chart(behavior,{type:'bar',data:{labels:['Detection','Specific detection','False positives','Held for approval'],datasets:[{label:'Strict',data:[100,100,0,71.4],backgroundColor:'#202633',borderRadius:4,barPercentage:.65},{label:'Balanced',data:[100,100,0,14.3],backgroundColor:accent,borderRadius:4,barPercentage:.65}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:'y',plugins:{legend},scales:{x:{min:0,max:100,grid:{color:grid},border:{display:false},ticks:{callback:v=>v+'%'}},y:{grid:{display:false},border:{display:false}}}}});
  const latency=document.getElementById('latencyChart');if(latency)new Chart(latency,{type:'line',data:{labels:['p50','p95','p99'],datasets:[{label:'Composed fence latency (ms)',data:[10.809,12.887,17.219],borderColor:technical,backgroundColor:'rgba(92,143,216,.08)',fill:true,tension:.3,pointBackgroundColor:'#fff',pointBorderColor:technical,pointBorderWidth:2,pointRadius:4,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},border:{display:false}},y:{beginAtZero:true,grid:{color:grid},border:{display:false},ticks:{callback:v=>v+' ms'}}}}});
  const assurance=document.getElementById('assuranceChart');if(assurance)new Chart(assurance,{type:'doughnut',data:{labels:['Compatibility','Fuzz / chaos','Release certification','Container scan'],datasets:[{data:[100,100,100,100],backgroundColor:[verified,technical,accent,'#9aa6b7'],borderColor:'#f7f8fb',borderWidth:4,hoverOffset:3}]},options:{responsive:true,maintainAspectRatio:false,cutout:'76%',plugins:{legend}}});
})();