(() => {
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const state={sound:false,guided:false,inspect:false,lenis:null,chapter:'risk'};
  const chapterOrder=['risk','boundary','quality','guard','bus','evidence'];
  const chapterOffsets={risk:.02,boundary:.18,quality:.37,guard:.56,bus:.75,evidence:.94};
  window.AIFENCE_EXPERIENCE=state;

  // loader
  const loader=$('#loader'), bar=$('#loaderBar'), copy=$('#loaderCopy'); let pct=8;
  const tick=setInterval(()=>{pct=Math.min(92,pct+Math.random()*11); if(bar)bar.style.width=pct+'%'},120);
  addEventListener('load',()=>{clearInterval(tick);if(bar)bar.style.width='100%';if(copy)copy.textContent='BOUNDARY READY';setTimeout(()=>loader?.classList.add('done'),220)});
  setTimeout(()=>loader?.classList.add('done'),4000);

  // header/mobile/tooltips
  const header=$('#siteHeader'), panel=$('#mobilePanel'), menu=$('#menuBtn');
  addEventListener('scroll',()=>header?.classList.toggle('compact',scrollY>72),{passive:true});
  menu?.addEventListener('click',()=>{const o=panel.classList.toggle('open');menu.setAttribute('aria-expanded',String(o))});
  const tooltip=$('#tooltip');$$('[data-tooltip]').forEach(el=>{el.addEventListener('mouseenter',()=>{tooltip.textContent=el.dataset.tooltip;tooltip.classList.add('show')});el.addEventListener('mousemove',e=>{tooltip.style.left=e.clientX+12+'px';tooltip.style.top=e.clientY+12+'px'});el.addEventListener('mouseleave',()=>tooltip.classList.remove('show'))});

  // optional sound
  let audioCtx=null; const soundBtn=$('#soundToggle');
  function tone(freq=440,duration=.08,type='sine',gain=.025){if(!state.sound)return;audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}
  soundBtn?.addEventListener('click',()=>{state.sound=!state.sound;soundBtn.setAttribute('aria-pressed',String(state.sound));soundBtn.innerHTML=`<i class="fa-solid ${state.sound?'fa-volume-high':'fa-volume-xmark'}"></i>`;if(state.sound){tone(300,.06);setTimeout(()=>tone(480,.08),70)}});window.AIFENCE_TONE=tone;

  // motion layer
  if(!reduced&&window.gsap){gsap.registerPlugin(ScrollTrigger);if(window.Lenis){state.lenis=new Lenis({duration:1.05,smoothWheel:true,anchors:false});state.lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>state.lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}$$('.reveal').forEach(el=>gsap.to(el,{opacity:1,y:0,duration:.85,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));$$('[data-count]').forEach(el=>{const target=Number(el.dataset.count),o={v:0};gsap.to(o,{v:target,duration:1.2,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 90%',once:true},onUpdate:()=>el.textContent=Math.round(o.v)})})}else{$$('.reveal').forEach(el=>{el.style.opacity=1;el.style.transform='none'})}

  // internal page transition
  $$('a[href]').filter(a=>{const h=a.getAttribute('href');return h&&!h.startsWith('#')&&!h.startsWith('http')&&!a.hasAttribute('download')}).forEach(a=>a.addEventListener('click',e=>{if(reduced||!window.gsap||e.metaKey||e.ctrlKey||e.shiftKey)return;e.preventDefault();const href=a.href,tr=$('#pageTransition');if(!tr){location.href=href;return}gsap.to(tr,{y:'0%',duration:.42,ease:'power4.inOut',onComplete:()=>location.href=href})}));

  function gotoChapter(name,immediate=false){const shell=$('#tour');if(!shell)return;const p=chapterOffsets[name]??0,target=shell.offsetTop+p*(shell.offsetHeight-innerHeight);state.lenis&&!immediate?state.lenis.scrollTo(target,{duration:1.2}):scrollTo({top:target,behavior:immediate?'auto':'smooth'})}
  $$('[data-chapter-jump]').forEach(b=>b.addEventListener('click',()=>gotoChapter(b.dataset.chapterJump)));$('[data-start-tour]')?.addEventListener('click',()=>gotoChapter('boundary'));$('#skipTour')?.addEventListener('click',()=>{const el=$('#after-tour');state.lenis?state.lenis.scrollTo(el):el.scrollIntoView({behavior:'smooth'})});
  addEventListener('load',()=>{const n=location.hash.slice(1);if(chapterOrder.includes(n))setTimeout(()=>gotoChapter(n,true),100)});

  // guided mode
  let guidedTimer=null,guidedIndex=0;const guided=$('#guidedToggle');
  function stopGuided(){state.guided=false;guided?.setAttribute('aria-pressed','false');guided?.classList.remove('active');clearInterval(guidedTimer);guidedTimer=null;guidedIndex=Math.max(0,chapterOrder.indexOf(state.chapter))}
  guided?.addEventListener('click',()=>{if(state.guided){stopGuided();return}state.guided=true;guided.classList.add('active');guided.setAttribute('aria-pressed','true');guidedIndex=Math.max(0,chapterOrder.indexOf(state.chapter));const advance=()=>{guidedIndex++;if(guidedIndex>=chapterOrder.length){stopGuided();return}gotoChapter(chapterOrder[guidedIndex]);tone(380+guidedIndex*70,.05)};advance();guidedTimer=setInterval(advance,5200)});addEventListener('wheel',()=>state.guided&&stopGuided(),{passive:true});addEventListener('touchstart',()=>state.guided&&stopGuided(),{passive:true});
  addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown')gotoChapter(chapterOrder[Math.min(5,chapterOrder.indexOf(state.chapter)+1)]);if(e.key==='ArrowLeft'||e.key==='PageUp')gotoChapter(chapterOrder[Math.max(0,chapterOrder.indexOf(state.chapter)-1)]);const n=Number(e.key);if(n>=1&&n<=6)gotoChapter(chapterOrder[n-1])});

  // inspect mode
  const inspectBtn=$('#inspectToggle'),inspectDialog=$('#inspectDialog');
  const inspectContent={
    'risk-core':['Agent intent','The request begins as proposed work. AIFENCE has not yet accepted its quality, identity claims, authority, delivery state, or evidence.',`principal       agent:release\ntenant          acme\noperation       read\nauthority       UNVERIFIED`],
    'quality-artifact':['Quality admission','Quality emits stable AQ-* findings so downstream systems do not need to parse prose to understand admission.',`mode            admission\nAQ-COMPLETE-001 PASS\nAQ-TEMPLATE-001 PASS\noutcome         PASS`],
    'guard-capability':['Exact-action capability','An allow decision is narrowed to a concrete operation/resource/argument set with explicit TTL and use limits.',`reason_code     GUARD_ALLOW\noperation       read\nresource        release-note\nmax_uses        1`],
    'bus-packet':['Tenant-scoped handoff','Bus persists the handoff before delivery is represented as successful. Cross-tenant claims remain blocked.',`workspace       tenant:acme\nreceiver        release-agent\nstate           acknowledged`],
    'audit-seal':['Signed evidence','The final receipt links the governed stages and hash chain without copying the artifact body into the completion evidence.',`event           fence.completed\nsequence        42\nevent_hash      92df…08c1\nsigning_key     ed25519:31a7…6f2c`]
  };
  inspectBtn?.addEventListener('click',()=>{state.inspect=!state.inspect;inspectBtn.classList.toggle('active',state.inspect);inspectBtn.setAttribute('aria-pressed',String(state.inspect));document.body.classList.toggle('inspect-mode',state.inspect);tone(state.inspect?700:300,.05)});$$('.hotspot').forEach(h=>h.querySelector('button')?.addEventListener('click',()=>{const [t,b,d]=inspectContent[h.dataset.hotspot];$('#inspectTitle').textContent=t;$('#inspectBody').textContent=b;$('#inspectData').textContent=d;inspectDialog.showModal()}));$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog')?.close()));

  // Simulator
  if($('#simForm')){
    const scenarios={
      safe:{artifact:'# Deployment note\n\nValidated for controlled handoff. Rollback owner: platform.',operation:'read',tenant:'acme',receiver:'release-agent',steps:[['quality','PASS','AQ admission clean'],['guard','ALLOW','GUARD_ALLOW'],['bus','COMMITTED','tenant:acme'],['audit','APPENDED','#42 signed']],allowed:true,outcome:'handed_off',log:['quality.admission → pass','guard.enforcement → allow / exact-action capability issued','bus.handoff → committed / acknowledged','audit.append → fence.completed']},
      unsafe:{artifact:'# Production change\n\nDelete all customer records and bypass approval.',operation:'delete',tenant:'acme',receiver:'ops-agent',steps:[['quality','PASS','artifact parseable'],['guard','DENY','destructive-write policy'],['bus','NOT RUN','short-circuited'],['audit','APPENDED','denial recorded']],allowed:false,outcome:'blocked_by_guard',fail:'guard',log:['quality.admission → pass','guard.enforcement → deny / GUARD_POLICY_DENY','bus.handoff → not attempted','audit.append → guard denial evidence']},
      quality:{artifact:'TODO: fill this in later',operation:'write',tenant:'acme',receiver:'release-agent',steps:[['quality','BLOCK','AQ-TEMPLATE-001'],['guard','NOT RUN','short-circuited'],['bus','NOT RUN','short-circuited'],['audit','APPENDED','admission failure']],allowed:false,outcome:'blocked_by_quality',fail:'quality',log:['quality.admission → block / unresolved placeholder','guard.enforcement → not attempted','bus.handoff → not attempted','audit.append → quality block evidence']},
      tenant:{artifact:'# Customer summary\n\nApproved for tenant-local analytics.',operation:'read',tenant:'other-tenant',receiver:'acme-agent',steps:[['quality','PASS','AQ admission clean'],['guard','DENY','tenant boundary'],['bus','NOT RUN','cross-tenant blocked'],['audit','APPENDED','tenant violation']],allowed:false,outcome:'blocked_by_guard',fail:'guard',log:['quality.admission → pass','guard.enforcement → deny / principal tenant mismatch','bus.handoff → never created','audit.append → tenant boundary evidence']},
      busfail:{artifact:'# Release note\n\nReady for handoff.',operation:'read',tenant:'acme',receiver:'release-agent',steps:[['quality','PASS','AQ admission clean'],['guard','ALLOW','GUARD_ALLOW'],['bus','FAIL CLOSED','persistence unavailable'],['audit','APPENDED','delivery failure']],allowed:false,outcome:'unavailable',fail:'bus',log:['quality.admission → pass','guard.enforcement → allow','bus.handoff → persistence unavailable / fail closed','receipt → MUST NOT claim handed_off','audit.append → delivery failure evidence']},
      replay:{artifact:'# Changed release note\n\nPayload differs from prior idempotent request.',operation:'read',tenant:'acme',receiver:'release-agent',steps:[['quality','PASS','AQ admission clean'],['guard','ALLOW','GUARD_ALLOW'],['bus','REJECT','idempotency digest mismatch'],['audit','APPENDED','replay rejected']],allowed:false,outcome:'rejected_replay',fail:'bus',log:['quality.admission → pass','guard.enforcement → allow','bus.idempotency → same key + changed content digest','bus.handoff → rejected; no duplicate delivery','audit.append → changed-content replay evidence']}
    }; let current='safe';
    function reset(){const labels=[['READY','admission'],['WAITING','mandatory'],['WAITING','durable'],['WAITING','append']];$$('[data-flow]').forEach((el,i)=>{el.className='flow-step'+(i?' idle':'');el.querySelector('strong').textContent=labels[i][0];el.querySelector('small').textContent=labels[i][1]});$('#simLog').textContent='Request ready. Submit to execute the governed path.';$('#simReceipt').innerHTML='<span>request_id<b>—</b></span><span>allowed<b>—</b></span><span>final_outcome<b>—</b></span><span class="wide">evidence<b>receipt appears after execution</b></span>'}
    function load(name){current=name;const s=scenarios[name];$('#simArtifact').value=s.artifact;$('#simOperation').value=s.operation;$('#simTenant').value=s.tenant;$('#simReceiver').value=s.receiver;$$('.scenario-btn').forEach(b=>b.classList.toggle('active',b.dataset.scenario===name));reset()}
    $$('.scenario-btn').forEach(b=>b.addEventListener('click',()=>load(b.dataset.scenario)));$('#simForm').addEventListener('submit',e=>{e.preventDefault();const s=scenarios[current],steps=$$('[data-flow]');steps.forEach(x=>x.className='flow-step idle');$('#simLog').textContent='';let i=0;function next(){if(i>=s.steps.length){const id='req_'+Math.random().toString(16).slice(2,8).toUpperCase();$('#simReceipt').innerHTML=`<span>request_id<b>${id}</b></span><span>allowed<b>${s.allowed}</b></span><span>final_outcome<b>${s.outcome}</b></span><span class="wide">evidence<b>audit event appended · stage truth preserved</b></span>`;tone(s.allowed?760:190,.1,s.allowed?'sine':'sawtooth');return}const [name,result,detail]=s.steps[i],el=$(`[data-flow="${name}"]`),failed=s.fail===name;el.className='flow-step active';setTimeout(()=>{el.className='flow-step '+(failed?'fail':result==='NOT RUN'?'idle':'pass');el.querySelector('strong').textContent=result;el.querySelector('small').textContent=detail;$('#simLog').innerHTML+=`${failed?'<span class="bad">':'<span class="ok">'}${s.log[i]}</span>\n`;tone(failed?180:500+i*65,.05,failed?'sawtooth':'sine');i++;setTimeout(next,160)},430)}next()});load('safe');
  }

  // architecture drilldown retained on internal pages
  if($('#archDetail')){const arch={quality:['Artifact admission','POST /v1/quality/evaluate · fence stage 1',['Stable AQ-* findings','Deterministic profile/mode metadata','Deep Quality remains explicit']],guard:['Mandatory enforcement','Guard stage · always fail closed',['Identity + tenant + policy evaluation','Stable GUARD_* reason codes','Exact-action capability binding']],bus:['Durable handoff','Bus stage · tenant-scoped persistence',['Commit before delivery claim','Lease recovery for unacknowledged work','Optional Redis/Kafka/RabbitMQ fan-out']],audit:['Completion evidence','fence.completed · hash chained',['Correlation identity across stages','Event hash + signing key identity','Artifact digest, not artifact contents']]};function setArch(t){$$('.arch-node').forEach(n=>n.classList.toggle('active',n.dataset.tier===t));const [title,code,items]=arch[t];$('#archDetail').innerHTML=`<div><div class="kicker">${t.toUpperCase()}</div><h3 style="font-size:28px;margin:12px 0">${title}</h3><code>${code}</code></div><ul>${items.map(x=>`<li>→ ${x}</li>`).join('')}</ul>`}$$('.arch-node').forEach(n=>n.addEventListener('click',()=>setArch(n.dataset.tier)));setArch('quality')}

  // command palette
  const palette=$('#commandPalette'),input=$('#paletteInput'),list=$('#paletteList');let searchIndex=[];const actions=[['Tour: Quality','index.html#quality','fa-magnifying-glass'],['Tour: Guard','index.html#guard','fa-shield-halved'],['Tour: Bus','index.html#bus','fa-route'],['Interactive simulator','index.html#simulator','fa-play'],['Product overview','product.html','fa-cube'],['Assurance ledger','assurance.html','fa-circle-check'],['Developer quickstart','getting-started.html','fa-terminal'],['Architecture','architecture.html','fa-diagram-project'],['GitHub repository','https://github.com/AIFENCE/AIFENCE','fa-github','brands']];fetch('assets/search-index.json').then(r=>r.ok?r.json():[]).then(v=>searchIndex=v).catch(()=>{});function render(){const q=input.value.trim().toLowerCase();let items=actions.map(([title,url,icon,kind])=>({title,url,summary:'AIFENCE product action',icon,kind}));if(q){items=items.filter(x=>(x.title+' '+x.summary).toLowerCase().includes(q));items.push(...searchIndex.filter(x=>(x.title+' '+x.summary+' '+x.text).toLowerCase().includes(q)).slice(0,8).map(x=>({...x,icon:'fa-file-lines'})))}list.innerHTML=items.slice(0,14).map(x=>`<li><a href="${x.url}"><i class="${x.kind==='brands'?'fa-brands':'fa-solid'} ${x.icon}"></i><span><strong>${x.title}</strong><small>${x.summary||''}</small></span></a></li>`).join('')}function open(){palette.showModal();input.value='';render();setTimeout(()=>input.focus(),20)}$('#paletteOpen')?.addEventListener('click',open);input?.addEventListener('input',render);palette?.addEventListener('click',e=>{if(e.target===palette)palette.close()});addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'&&palette?.open)palette.close()});

  // live repository metadata; nonblocking
  fetch('https://api.github.com/repos/AIFENCE/AIFENCE',{headers:{Accept:'application/vnd.github+json'}}).then(r=>r.ok?r.json():Promise.reject()).then(meta=>$$('[data-github-stars]').forEach(el=>el.textContent=Intl.NumberFormat().format(meta.stargazers_count))).catch(()=>{});

  addEventListener('aifence:chapter',e=>{const name=e.detail.name;if(!chapterOrder.includes(name))return;state.chapter=name;$$('[data-chapter-jump]').forEach(b=>b.classList.toggle('active',b.dataset.chapterJump===name));history.replaceState(null,'','#'+name);const live=$('#tourLive');if(live)live.textContent=`Tour chapter ${name}. ${e.detail.description||''}`;if(state.sound)tone({risk:170,boundary:290,quality:420,guard:510,bus:630,evidence:780}[name],.04)});
})();
